### ISSUE TITLE
32. Audience - the example of audiences is restricted

### ISSUE THREAD

**Issue by ACz-UniBi** [openaire/guidelines-literature-repositories#15]
The resource of http://www.ed.gov/admin/reference/index.jsp
isn't free accessible. 

Msg:
_Access to the page you requested is restricted. If you feel that you have received this notice in error, please contact the ED.gov webmaster at webmaster@ed.gov. Thank you._

No good example for OpenScience and OpenData. It's not transparent.

**Comment by ACz-UniBi** [comment]
What's the difference between:

- Student Financial Aid Providers
- Students

?

**Comment by joschirr** [comment]
The link and vocabulary were introduced in the DRIVER-II guidelines, https://wiki.surfnet.nl/display/DRIVERguidelines/Audience
but have their roots in the DCMI Education Community, http://www.dublincore.org/groups/education/Audience-Level-Proposal/
Because this old link (http://www.ed.gov/admin/reference/index.jsp) is either no longer  valid or just not public we may link to the "Common Education Data Standards" (still part of the U.S. department of education),
https://ceds.ed.gov/element/001492
and pick some values for the vocabulary.
